### ISSUE TITLE
VSTS bot should hide conversations that other users don't need to see

### ISSUE THREAD

**Issue by eoliver692** [ALM-Rangers/DevOps-VSTS-Bot#113]
When VSTS bot asks me to connect in the slack channel, all the prompts etc are visible to all users in the channel. Anything other users do not need to see should be marked as visible to only me if possible.

**Comment by jeffrey-opdam** [comment]
Thank you for your feedback.

Sorry, as far as I know it is not possible to hide message for certain users in a Slack channel.
We took some effort to make sure that another user can get your credentials or access to your VSTS account.

Would it be helpful if we only allow you to connect to VSTS through a private chat? Still allowing other commands on the Channels?

**Comment by jeffrey-opdam** [comment]
Closing, no response.
