### ISSUE TITLE
"Object reference not set to an instance of an object" when not connected

### ISSUE THREAD

**Issue by tomkerkhove** [ALM-Rangers/DevOps-VSTS-Bot#114]
I installed a fresh install of the bot and typed `build` which cased a "Object reference not set to an instance of an object" because I was not connected.

Would it be possible to handle this and instead reply that I need to authenticate?

**Comment by jeffrey-opdam** [comment]
I would expect it to offer you some help, (which is only 'connect' if you not done so before).
Do you still have this issue?

**Comment by jeffrey-opdam** [comment]
Closing due to no response.
