### ISSUE TITLE
invalid identity. assignedToFilter parameter

### ISSUE THREAD

**Issue by forktrucka** [ALM-Rangers/DevOps-VSTS-Bot#119]
Hi, I recently updated my displayname in VSTS. Now using the approvals command doesn't work via slack (haven't tried other channels). 

*Error occurred:* VS4029131: Invalid identity [old displayname] specified in assignedToFilter parameter. Make sure that the value is a valid identity ID or identity name and try again.

Also, have tried uninstalling and reinstalling the bot from slack, and trying to reconnect to vsts. No luck, trying to reconnect throws a different error. When i try to reconnect, i can see my vsts instance, but trying to connect throws *Error occurred:* Value cannot be null. Parameter name: value

**Comment by jeffrey-opdam** [comment]
Can you run ' /deleteprofile'. Do not forget the space before the /.

**Comment by forktrucka** [comment]
ah yep. Was able to delete the profile and reconnect. fixing the issue. 

Guessing you should be able to update your display name in the future without it totally breaking though right?
