### ISSUE TITLE
Approvals do not seem to work with groups?

### ISSUE THREAD

**Issue by mkporwit** [ALM-Rangers/DevOps-VSTS-Bot#120]
If I define a pre-deployment approval as requiring sign-off from someone in a group, and I am a member of that group, when I run "approvals" I am told there are none. If I am listed explicitly, by name, instead of by group membership, then approvals work as expected.

Not showing approvals for group members is a major issue for us, as we have deployment approvals that require Person X, Person Y, and (A or B or C), and groups is how we express those requirements.

**Comment by jeffrey-opdam** [comment]
We will look into it. Thank you for reporting it.

**Comment by mkporwit** [comment]
Thanks. Let me know if there is any diagnostic/debug info you'd like from us, whether logs or http dumps

**Comment by jeffrey-opdam** [comment]
Yes, 
Can you tell me if you used a Application Group (those within vsts), or connected an Azure Active Directory security group?

**Comment by mkporwit** [comment]
These were groups created inside the project in VSTS, not AD groups. I'm not an AD admin.
