### ISSUE TITLE
uninstalling and reinstalling of VSTSBot results in connection problems

### ISSUE THREAD

**Issue by mkporwit** [ALM-Rangers/DevOps-VSTS-Bot#125]
I uninstalled the VSTSBot integration and reinstalled it, hoping to pick up the group approvals fix. Unfortunately, I am unable to connect the bot to the account again. When I type connect, it shows the existing project that it used to be connected to prior to uninstall, and then when I select that project it errors out complaining of null parameters:
<img width="499" alt="screen shot 2018-02-08 at 10 21 58 am" src="https://user-images.githubusercontent.com/1071847/35990841-3b3e8208-0cba-11e8-9b98-753739b11b98.png">

**Comment by jeffrey-opdam** [comment]
Just type ' /deleteprofile' do not forget the space.

The fix will not be there until saturday. At which you will need to connect. But you do not have to uninstall and install the bot. Our deployments are server side only.

On Feb 8, 2018 7:25 PM, Marcin Porwit <notifications@github.com> wrote:

I uninstalled the VSTSBot integration and reinstalled it, hoping to pick up the group approvals fix. Unfortunately, I am unable to connect the bot to the account again. When I type connect, it shows the existing project that it used to be connected to prior to uninstall, and then when I select that project it errors out complaining of null parameters:
[screen shot 2018-02-08 at 10 21 58 am]<https://user-images.githubusercontent.com/1071847/35990841-3b3e8208-0cba-11e8-9b98-753739b11b98.png>

**Comment by mkporwit** [comment]
OK, thanks, that ' /deleteprofile' seems to do the trick. I'll wait 'till next week to test group approvals then.
